[connections_gcs]
type = "service_account"
project_id = "footbalprediction-414107"
private_key_id = "ccae027241adbd582a4b8c05a4d530ab9089327a"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCl6OkIEh6U3ES4\n...snipped...\n-----END PRIVATE KEY-----\n"
client_email = "streamlit-python-0410@footbalprediction-414107.iam.gserviceaccount.com"
client_id = "114047689527607639710"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-python-0410%40footbalprediction-414107.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

